### ISSUE TITLE
Roadmap to first release?

### ISSUE THREAD

**Issue by Magnati** [nayan32biswas/mongodb-odm#3]
Dear Nayan,

I stumbled over this raw diamond and like it allot. 
High potential and kind of the solution I was not looking for. ^^

I see that you latest tag is an alpha tag,  `0.1.0a3`.
Do you have something like a feature plan, or a roadmap?
Maybe a participation plan...?

Would nice to get feedback from You.

**Comment by vigintuple** [comment]
Currently, I am writing the doc and the target was to finish the doc first.
You can find multiple fixes and initial documentation on the `doc` branch. I am working in that branch.

So roadmap to the next release was,
- Complete the doc and published it.
- And make sure all the test case was covered.

Roadmap to first development release,
- Implement all the features with a demo project probably in [this](https://github.com/vigintuple/fastapi-blog) repository.

**Comment by nayan32biswas** [comment]
Hi @Magnati, we release our first version **0.2.0**.
We will be very happy if you review the documentation or source code.
