### ISSUE TITLE
Tests on index creation are failing

### ISSUE THREAD

**Issue by Magnati** [nayan32biswas/mongodb-odm#30]
Hey @nayan32biswas ,

I stumbled upon that your action-pipeline has failed: https://github.com/nayan32biswas/mongodb-odm/actions/runs/9042699610/job/24849524752

Since Index-Creation out of the box is a pretty neat feature of your lib I wonder what caused it?
Newer mongodb image?
<img width="1010" alt="Bildschirmfoto 2024-07-05 um 13 22 10" src="https://github.com/nayan32biswas/mongodb-odm/assets/9417155/106f4aa5-2d15-4e36-b47a-2ce02d4cc5b8">

**Comment by nayan32biswas** [comment]
The issue is fixed under PR #35.
Thanks for raising the issue.
